# This is a basic workflow to help you get started with Actions

name: Docker Build

on: [push]

jobs:
 
  build:

    runs-on: ubuntu-latest

   
    steps:
     
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # - name: docker login
      #   env:
      #     DOCKER_USER: ${{secrets.DOCKER_USER}}
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #   run: |
      #     docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
          
      - name: build angular
        run: |
          docker build ./ordersApp -t ft-ribeiro/orders-app:1.0.0
