# This is a basic workflow to help you get started with Actions

name: Docker Build

on: [push]

jobs:
 
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      
      - uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}    
      - name: docker Login
        run: |
          docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD

      - name: build angular
        run: |
          docker build ./ordersApp -t ft-ribeiro/orders-app:1.0.0
      - name: Logout
        run: |
          docker logout
          docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
      - name: Push image
        run: |
          docker push ft-ribeiro/orders-app:1.0.0